In [3]:
import torch
import numpy as np


In [4]:
x = torch.tensor([1., 2., 3.])
x, x.shape, x.dtype, x.device


(tensor([1., 2., 3.]), torch.Size([3]), torch.float32, device(type='cpu'))

In [5]:
x * torch.rand(3)

tensor([0.3401, 0.4495, 0.6950])

In [6]:
torch.stack([x, x, x], dim=0)

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])

In [7]:
# reshape
y = torch.tensor([4., 5., 6.])
y.reshape(1,3,1), y.reshape(3, 1).squeeze()

(tensor([[[4.],
          [5.],
          [6.]]]),
 tensor([4., 5., 6.]))

In [7]:
# permute
image = torch.rand(16, 16, 3)
image.permute(2, 0, 1).shape

torch.Size([3, 16, 16])

In [8]:
# Indexing
x = torch.rand(5, 3)
x[0, 0], x[0, :], x[0:2, 0:2]

(tensor(0.2012),
 tensor([0.2012, 0.0358, 0.8137]),
 tensor([[0.2012, 0.0358],
         [0.1257, 0.0158]]))

In [15]:
# numpy
x = torch.tensor([1., 2., 3.])
y = np.array([1., 2., 3.])
torch.from_numpy(y), x.numpy()

(tensor([1., 2., 3.], dtype=torch.float64), array([1., 2., 3.], dtype=float32))

In [17]:
# warning
np.array(1.0).dtype, torch.from_numpy(np.array(1.0)).dtype

(dtype('float64'), torch.float64)